name: Build Releases
on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - mips-unknown-linux-musl
          - mipsel-unknown-linux-musl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"

      - name: Rename artifacts and compress
        run: |
          cd target/${{ matrix.target }}/release
          xz -k udp_listen_relay
          mv udp_listen_relay.xz udp_listen_relay_${{ matrix.target }}.xz

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/*.xz